### ISSUE TITLE
`:local/root` deps in `deps.edn`

### ISSUE THREAD

**Issue by camsaul** [drcode/good-guesser#1]
Would it be possible to change these deps

https://github.com/drcode/good-guesser/blob/master/deps.edn#L1-L2

to Git or maven deps? So we can try out your library locally without having to try to guess what the deps are supposed to be

**Comment by drcode** [comment]
Shoot, I thought I removed those- I will fix the next couple of days

**Comment by drcode** [comment]
OK now fixed, sorry for the wait.
